apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}

data:
  PUID: "{{ .Values.puid }}"
  PGID: "{{ .Values.pgid }}"
  TZ: "{{ .Values.tz }}"