apiVersion: v1
kind: Service

metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}

spec:
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}

  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
