apiVersion: v1
kind: Secret

metadata:
  name: {{ include "graylog.fullname" . }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}

data:
  GRAYLOG_PASSWORD_SECRET: "{{ .Values.auth.secret_hash | b64enc }}"
  GRAYLOG_ROOT_PASSWORD_SHA2: "{{ .Values.auth.password | sha256sum | b64enc}}"
  GRAYLOG_ROOT_USERNAME: "{{ .Values.auth.username | b64enc }}"