apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "graylog.fullname" . }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}

data:
  GRAYLOG_NODE_ID_FILE: "{{ .Values.config.nodeIdFile }}"
  GRAYLOG_HTTP_BIND_ADDRESS: "{{ .Values.config.bindAddress }}"
  GRAYLOG_HTTP_EXTERNAL_URI: "{{ .Values.config.grayLogUri }}"
  GRAYLOG_ELASTICSEARCH_HOSTS: "{{ .Values.config.elasticsearchHost }}"
  GRAYLOG_MONGODB_URI: "{{ .Values.config.mongoDbUri }}"
  GRAYLOG_ROOT_TIMEZONE: "{{ .Values.config.tz }}"