apiVersion: v1
kind: PersistentVolume

metadata:
  name: {{ include "graylog.fullname" . }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}

spec:
  capacity:
    storage: "{{ .Values.volume.size }}"
    
  accessModes: ["{{ .Values.volume.accessModes }}"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volume.storageClassName }}

  mountOptions:
    - hard
    - nfsvers=3

  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
    readOnly: false