---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "graylog.fullname" . }}
  labels:
    {{- include "graylog.labels" . | nindent 4 }}

spec:
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes: ["{{ .Values.volume.accessModes }}"]
    
  resources:
    requests:
      storage: "{{ .Values.volume.size }}"