---
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}

data:
  TZ: "{{ .Values.tz }}"
  PUID: "{{ .Values.puid }}"
  PGID: "{{ .Values.pgid }}"
  UMASK: "022"
