apiVersion: v1
kind: PersistentVolume

metadata:
  name: {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}

spec:
  capacity:
    storage: {{ .Values.volume.size }}

  accessModes: 
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain
  storageClassName: worland-raid

  mountOptions:
    - hard
    - nfsvers=3

  claimRef:
    name: {{ include "heimdall.fullname" . }}
    namespace: {{ .Release.Namespace }}
    
  nfs:
    server: 192.168.100.14
    path: "/volume2/Cluster_Raid_Storage"
    readOnly: false