---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}

spec:
  storageClassName: worland-raid

  accessModes:
    - ReadWriteMany
    
  resources:
    requests:
      storage: {{ .Values.volume.size }}