apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}

data:
  discovery.type: "single-node"
  network.host: "0.0.0.0"
  transport.host: "0.0.0.0"
  cluster.name: "es-data-cluster"
  node.name: es-node
  bootstrap.memory_lock: "true"
  discovery.zen.minimum_master_nodes: "1"
  xpack.license.self_generated.type: trial
  xpack.security.enabled: "false"
  ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
  action.auto_create_index: "false"