apiVersion: v1
kind: Secret

metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}

data:
  POSTGRES_USER: "{{ .Values.auth.username | b64enc }}"
  POSTGRES_PASSWORD: "{{ .Values.auth.password | b64enc}}"