apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}

data:
  POSTGRES_DB: "{{ .Values.config.postgresDb }}"
  PGDATA: "{{ .Values.config.pgData }}"