apiVersion: v1
kind: Service

metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Release.Namespace }}

spec:
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}

  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}

  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: database