apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    
data:
  redis-config: |-
    bind {{ .Values.config.bind }}
    {{- if .Values.config.appendOnly }}
    appendonly yes
    {{- end }}
    {{- if .Values.config.socket }}
    unixsocket /data/redis.sock
    unixsocketperm 755
    {{- end }}
    {{- if .Values.auth.enabled }}
    protected-mode yes
    requirepass {{ .Values.auth.password }}
    user {{ .Values.auth.username }} allcommands allkeys on >{{ .Values.auth.password }}
    {{- end }}

