apiVersion: v1
kind: Service

metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Release.Namespace }}

spec:
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}

  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}

  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: database