apiVersion: v1
kind: Secret

metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}

data:
  ADMIN_EMAIL: {{ .Values.admin.email | b64enc }}
  WEBPASSWORD: {{ .Values.admin.password | b64enc }}
