apiVersion: v1
kind: Service

metadata:
  name: {{ include "pihole.fullname" . }}-udp
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "pihole.fullname" . }}
    
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}

  ports:
    - name: dns
      port: 53
      targetPort: 53
      protocol: UDP
    - name: bootps
      port: 67
      targetPort: 67
      protocol: UDP

  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
