apiVersion: v1
kind: Service

metadata:
  name: {{ include "pihole.fullname" . }}-tcp
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "pihole.fullname" . }}

spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}

  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP

  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
