apiVersion: v1
kind: Secret

metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}

data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.username | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.auth.password | b64enc}}