apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}

data:
  MONGO_INITDB_DATABASE: "{{ .Values.config.mongoDb }}"