apiVersion: v1
kind: Service

metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Release.Namespace }}

spec:
  selector:
    {{- include "mongo.selectorLabels" . | nindent 4 }}
    
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  
  ports:
    - name: mongo
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: database