replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: "4.4" # Cannot get 5 to work

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

auth:
  username: "mongo"
  password: "IamIronMan!"

config:
  mongoDb: "mongo"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.2
  externalTrafficPolicy: Cluster
  port: 27017

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

volume:
  storageClassName: "raid"
  size: "10Gi"
  accessModes: "ReadWriteOnce"

nfs:
  server: "192.168.0.2"
  path: "/path/to/volume"
  subPath: "mongo"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
